version: "3"

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mariadb
    container_name: db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: test123
